### PR TITLE
Remove invisible.vbs and use conhost --headless instead

### PR DESCRIPTION
**Pull request by Romanitho**
@KnifMelti I think I got it :)

### CODE REVIEW

**Comment by KnifMelti** [comment]
What!
And all those threads discussing the problem all over time and place...
...conhost.exe
How/where did you hear of it?

**Comment by Romanitho** [comment]
ChatGPT 😅😅😅

**Comment by KnifMelti** [comment]
And for me GhatGPT says:

Conclusion:
conhost.exe does not take a --headless parameter or any other command-line parameters.
If you want to run PowerShell or another console application without displaying a window, use the -WindowStyle Hidden parameter with powershell.exe.

**Comment by KnifMelti** [comment]
But in cmd `conhost.exe --headless powershell.exe` starts powershell headless! 👌
ChatGPT wrong for me, right for you...

**Comment by KnifMelti** [comment]
But, [Perplexity](https://www.perplexity.ai/) says:
Using `conhost.exe --headless powershell.exe` to start PowerShell in a headless mode is possible, but there are some considerations to keep in mind. The `--headless` mode is intended to prevent any UI from appearing, which can be useful for running scripts without displaying a console window[2][5]. However, there are known issues with this approach, such as `conhost.exe --headless` not exiting with the child process's exit code, which can lead to unexpected behavior in scripts that rely on exit codes[1].

Additionally, the `conhost.exe --headless` functionality has been described as broken in some contexts, and there are ongoing discussions about fixing these issues in future Windows builds[4]. Therefore, while you can technically use the command `conhost.exe --headless powershell.exe`, you should be aware of these limitations and potential issues.

Citations:
[1] https://github.com/microsoft/terminal/issues/17178
[2] https://www.reddit.com/r/PowerShell/comments/1cc1r5f/powershell_with_hiddenminimized_window_via_task/
[3] https://devblogs.microsoft.com/commandline/windows-command-line-inside-the-windows-console/
[4] https://github.com/microsoft/terminal/issues/13914
[5] https://mrd0x.com/introduction-to-parent-child-process-evasion/

**Comment by Romanitho** [comment]
I don't remember if I asked chatgpt or Copilot, to be honest 😅 but it's the same.

**Comment by KnifMelti** [comment]
Ah, I only have the standard ChatGPT.. ..anyway [Perplexity](https://www.perplexity.ai/) gave the correct answer!

**Comment by Romanitho** [comment]
Anyway, in my first tests it seems to work well.

**Comment by Romanitho** [comment]
At least with this approach, we get rid of vbs, and we do not have to handle an EXE launcher... let's see if it does the trick with our msi version before submitting any change in the main WAU repo.

**Comment by KnifMelti** [comment]
NB from Perplexity:
The upcoming Windows update is expected to address the issue with `conhost.exe --headless` not exiting with the child process's exit code. This improvement is linked to a pull request (#7337) that will allow PowerShell to completely prevent a window from being created, which should help resolve the problem. This fix is anticipated to be available in future Windows versions later this year[4].

Citations:
[1] https://github.com/microsoft/terminal/actions/runs/8946285267/job/24576675582
[2] https://github.com/microsoft/terminal/issues/13914
[3] https://detection.fyi/the-dfir-report/sigma-rules/windows/process_creation/proc_creation_win_conhost_headless/
[4] https://github.com/microsoft/terminal/issues/17178
[5] https://splunkresearch.com/endpoint/d5039508-998d-4cfc-8b5e-9dcd679d9a62/

**Comment by Romanitho** [comment]
Should be good 😅

**Comment by KnifMelti** [comment]
This can also be used with the Shortcut **Run WAU** (avoiding the brief flashing of cmd windos):
`C:\Windows\System32\conhost.exe --headless C:\Windows\System32\schtasks.exe -run -tn WAU\Winget-AutoUpdate`

**Comment by Romanitho** [comment]
That's true

**Pull request merged**
