### PR TITLE
Update Update-WAU.ps1

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by KnifMelti** [comment]
As admin or as SYSTEM this happens:
image

**Comment by Romanitho** [comment]
I cannot reproduce the problem on a VM. strange

**Comment by Romanitho** [comment]
Ok, this happened when no checkbox was ticked. It should be fixed now with latest build. If you can confirm @KnifMelti :)

**Comment by KnifMelti** [comment]
Not so good:
image

**Comment by Romanitho** [comment]
Good for the registry.
On my VMs, it was not detected. It's so strange.
Maybe the vbs inside ? I don't know what can be wacatac...

**Comment by KnifMelti** [comment]
> On my VMs, it was not detected. It's so strange.

This was detected on my regular PC after downloading

**Comment by Romanitho** [comment]
I didn't change that much from the previous one 😅

**Comment by KnifMelti** [comment]
No, it's very weird.
Microsoft Defender Antivirus false positive.
Ran it through VirusTotal (theY doesn't include Microsoft Defender Antivirus) and all is good:
https://www.virustotal.com/gui/file/3718ae08236b0c1611d79449e2bb9ac285c6013decb85d547e8ec6e8017242db/detection

**Comment by KnifMelti** [comment]
Ah, maybe in **Behavior Sigma Rules**:
image

**Comment by KnifMelti** [comment]
**Sigma Rules** keeps adding info under **Behavior**, but **_No security vendors flagged this file as malicious_**:
https://www.virustotal.com/gui/file/3718ae08236b0c1611d79449e2bb9ac285c6013decb85d547e8ec6e8017242db/behavior

**Comment by Romanitho** [comment]
Okay. Maybe if the msi is downloaded several times, it will be "trusted" 😅

**Comment by Romanitho** [comment]
https://github.com/Romanitho/WAU-MSI/releases/tag/v1.22.6

**Comment by KnifMelti** [comment]
Tested the download on my company computer.
No problem at all (more than _This file is not downloaded often, do you want to keep it?_ from Microsoft Defender SmartScreen)
So, it looks like `Write-CMTraceLog.ps1` was the culprit.

**Pull request merged**
